routes/dashboard.php
<?php
Route::get('/suggestion', 'HomeController@suggestions')->name('suggestion');
Route::get('/message-today', 'MessageController@messagesToday')->name('message-today');
Route::get('/message-all', 'MessageController@messagesAll')->name('message-all');
Route::get('/message-reply/{id}', 'MessageController@message')->name('message.reply');

Route::get('/grapt-log', 'HomeController@graptLogs')->name('grapt-log');

routes/frontend.php
<?php
Route::get('/portal-source', 'WelcomeController@portalSource')->name('portal-source');
Route::get('/instance-source', 'WelcomeController@instanceSource')->name('instance-source');
Route::get('/wel/{scholarship}', 'WelcomeController@show')->name('show');
Route::post('/subscriber', 'SubscriberController@store')->name('subscriber.store');

Route::resource('/chat', 'ChatController')->except(['destroy']);;
Route::get('/chat-wel/{chat}', 'ChatController@chatWel')->name('chat-wel');
Route::resource('/forum', 'ForumController')->except(['destroy']);;
Route::get('/forum-wel/{forum}', 'ForumController@forumWel')->name('forum-wel');
Route::resource('/topic', 'TopicController');
Route::get('/message', 'MessageController@index')->name('message.index');
Route::post('/message', 'MessageController@store')->name('message.store');
Route::get('/', 'WelcomeController@index')->name('index');
Route::get('show/{scholarship}', 'WelcomeController@show')->name('show');

routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/


Auth::routes();
// require_once('frontend.php');
require_once('grapt.php');
require_once('component.php');
// require_once('auth.php');

Route::group(['middleware'=>['auth']],function() {

    require_once('dashboard.php');


    Route::get('/home', 'HomeController@index')->name('home');
    Route::get('/log', 'HomeController@log')->name('log');
    Route::get('/suggestion', 'HomeController@suggestion')->name('suggestion');
    Route::get('/ignore/{website}', 'HomeController@ignore')->name('ignore');

    Route::resource('/administrator', 'AdministratorController');
    Route::get('/get-administrators', 'AdministratorController@getAdministrators')->name('get-administrators');
    Route::resource('/configuration', 'ConfigurationController');
    Route::get('/get-configurations', 'ConfigurationController@getConfigurations')->name('get-configurations');
    Route::resource('/scholarship', 'ScholarshipController');
    Route::post('/scholarship-edit/{scholarship}', 'ScholarshipController@updateData')->name('update-data.scholarship-edit');
    Route::get('/period/{scholarship}/edit/', 'ScholarshipController@periodEdit')->name('edit.period');

    Route::get('/get-scholarships', 'ScholarshipController@getScholarships')->name('get-scholarships');
    Route::get('/subscriber', 'SubscriberController@index')->name('subscriber.index');
    Route::delete('/subscriber/{subscriber}', 'SubscriberController@destroy')->name('subscriber.destroy');
    Route::delete('/forum/{forum}', 'ForumController@destroy')->name('forum.destroy');
    Route::get('/get-forum', 'ForumController@getForums')->name('get-forum');
    Route::delete('/chat/{chat}', 'ChatController@destroy')->name('chat.destroy');
    Route::get('/get-chat/{forum_id}', 'ChatController@getChats')->name('get-chat');
    Route::get('/get-subscribers', 'SubscriberController@getSubscribers')->name('get-subscribers');
    Route::resource('/website', 'WebsiteController');
    Route::get('/get-websites', 'WebsiteController@getWebsites')->name('get-websites');

    Route::put('/message/{message}', 'MessageController@update')->name('message.put');
    Route::get('/message/{message}/edit', 'MessageController@edit')->name('message.edit');
    Route::get('get-fill-websites', 'WebsiteController@fillWebsite')->name('get-fill-websites');
    Route::get('get-fill-attributes', 'ScholarshipAttributeController@fillScholarshipAttribute')->name('get-fill-attributes');


    Route::resource('/scholarship-attribute', 'ScholarshipAttributeController');
    Route::get('/get-scholarshipattribute', 'ScholarshipAttributeController@getScholarshipAttribute')->name('get-scholarshipattribute');



    Route::get('/send/email', 'HomeController@mail');

    Route::get('/scraper-suggestion', 'ScaperController@google');
    Route::get('/year', 'ScaperController@year');
    Route::get('/scraper-web', 'ScaperController@website');
    Route::get('/subscriber-mail', 'SubscriberController@subscriberMail');


    });

    Route::view('/reply', 'email.name')->name('reply');
    Route::post('/reply', 'MessageController@reply')->name('reply');



    Route::get('/portal-source', 'WelcomeController@portalSource')->name('portal-source');
    Route::get('/quick-search/{query}', 'WelcomeController@quickSearch')->name('quick-search');

    Route::get('/instance-source', 'WelcomeController@instanceSource')->name('instance-source');
    Route::get('/wel/{scholarship}', 'WelcomeController@show')->name('show');
    Route::post('/subscriber', 'SubscriberController@store')->name('subscriber.store');

    Route::resource('/chat', 'ChatController')->except(['destroy']);;
    Route::get('/chat-wel/{chat}', 'ChatController@chatWel')->name('chat-wel');
    Route::resource('/forum', 'ForumController')->except(['destroy']);;
    Route::get('/forum-wel/{forum}', 'ForumController@forumWel')->name('forum-wel');
    Route::get('/message', 'MessageController@index')->name('message.index');
    Route::post('/message', 'MessageController@store')->name('message.store');
    Route::get('/', 'WelcomeController@index')->name('index');
    Route::get('show/{scholarship}', 'WelcomeController@show')->name('show');

resources/views/layouts/include/_footer.blade.php
<footer class="m-grid__item		m-footer ">
    <div class="m-container m-container--fluid m-container--full-height m-page__container">
        <div class="m-stack m-stack--flex-tablet-and-mobile m-stack--ver m-stack--desktop">
            <div class="m-stack__item m-stack__item--left m-stack__item--middle m-stack__item--last">
                <span class="m-footer__copyright">
                    2018 &copy; by <a href="https://github.com/Audhy" class="m-link">Audhy</a>
                </span>
            </div>
            <div class="m-stack__item m-stack__item--right m-stack__item--middle m-stack__item--first">
                <ul class="m-footer__nav m-nav m-nav--inline m--pull-right">
                    <li class="m-nav__item">
                        <a href="#" class="m-nav__link">
                            <span class="m-nav__link-text">About</span>
                        </a>
                    </li>
                    <li class="m-nav__item">
                        <a href="#" class="m-nav__link">
                            <span class="m-nav__link-text">Privacy</span>
                        </a>
                    </li>
                    <li class="m-nav__item">
                        <a href="#" class="m-nav__link">
                            <span class="m-nav__link-text">T&C</span>
                        </a>
                    </li>
                    <li class="m-nav__item">
                        <a href="#" class="m-nav__link">
                            <span class="m-nav__link-text">Purchase</span>
                        </a>
                    </li>
                    <li class="m-nav__item m-nav__item">
                        <a href="#" class="m-nav__link" data-toggle="m-tooltip" title="Support Center" data-placement="left">
                            <i class="m-nav__link-icon flaticon-info m--icon-font-size-lg3"></i>
                        </a>
                    </li>
                </ul>
            </div>
        </div>
    </div>
</footer>

resources/views/layouts/include/_header.blade.php
<title>{{ config('app.name', 'PortalBeasiswa') }}</title>

<meta charset="utf-8">
<meta name="description" content="">
<meta name="csrf-token" content="{{ csrf_token() }}">
<meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, shrink-to-fit=no">

<script src="https://ajax.googleapis.com/ajax/libs/webfont/1.6.16/webfont.js"></script>

<script>
    WebFont.load({
        google: {"families":["Poppins:300,400,500,600,700","Roboto:300,400,500,600,700"]},
        active: function() {
            sessionStorage.fonts = true;
        }
    });
</script>

<link rel="stylesheet" type="text/css" href="{{ asset('assets/metronic/vendors/custom/fullcalendar/fullcalendar.bundle.css') }}">

<link rel="stylesheet" type="text/css" href="{{ asset('assets/metronic/vendors/base/vendors.bundle.css') }}">
<link rel="stylesheet" type="text/css" href="{{ asset('assets/metronic/demo/default/base/style.bundle.css') }}">

<link rel="shortcut icon" href="{{ asset('assets/metronic/demo/default/media/img/logo/favicon.ico') }}">

resources/views/layouts/include/_nav-sticky.blade.php
<ul class="m-nav-sticky" style="margin-top: 30px;">
    <li class="m-nav-sticky__item" data-toggle="m-tooltip" title="Purchase" data-placement="left">
        <a href="https://themeforest.net/item/metronic-responsive-admin-dashboard-template/4021469?ref=keenthemes"
           target="_blank"><i class="la la-cart-arrow-down"></i></a>
    </li>
    <li class="m-nav-sticky__item" data-toggle="m-tooltip" title="Documentation" data-placement="left">
        <a href="https://keenthemes.com/metronic/documentation.html" target="_blank"><i class="la la-code-fork"></i></a>
    </li>
    <li class="m-nav-sticky__item" data-toggle="m-tooltip" title="Support" data-placement="left">
        <a href="https://keenthemes.com/forums/forum/support/metronic5/" target="_blank"><i class="la la-life-ring"></i></a>
    </li>
</ul>

resources/views/layouts/include/_sidebar.blade.php
<button class="m-aside-left-close  m-aside-left-close--skin-dark " id="m_aside_left_close_btn">
    <i class="la la-close"></i>
</button>

<div id="m_aside_left" class="m-grid__item	m-aside-left  m-aside-left--skin-dark ">
    <div id="m_ver_menu" class="m-aside-menu  m-aside-menu--skin-dark m-aside-menu--submenu-skin-dark " m-menu-vertical="1" m-menu-scrollable="1" m-menu-dropdown-timeout="500" style="position: relative;">		
        <ul class="m-menu__nav  m-menu__nav--dropdown-submenu-arrow ">
            <li class="m-menu__section">
                <h4 class="m-menu__section-text">
                    Main Menu
                </h4>
                <i class="m-menu__section-icon flaticon-more-v3"></i>
            </li>
            <li class="m-menu__item" aria-haspopup="true" data-menu-submenu-toggle="hover">
                <a href="{{ route('home') }}" class="m-menu__link m-menu__toggle">
                    <i class="m-menu__link-icon flaticon-line-graph"></i>
                    <span class="m-menu__link-text">Dashboard</span>
                </a>
            </li>
            <li class="m-menu__item" aria-haspopup="true" data-menu-submenu-toggle="hover">
                <a href="{{ route('website.index') }}" class="m-menu__link m-menu__toggle">
                    <i class="m-menu__link-icon flaticon-network"></i>
                    <span class="m-menu__link-text">
                        Website
                    </span>
                </a>
            </li>
            <li class="m-menu__item" aria-haspopup="true" data-menu-submenu-toggle="hover">
                <a href="{{ route('scholarship-attribute.index') }}" class="m-menu__link m-menu__toggle">
                    <i class="m-menu__link-icon flaticon-network"></i>
                    <span class="m-menu__link-text">
                        Attribute
                    </span>
                </a>
            </li>
            <li class="m-menu__item" aria-haspopup="true" data-menu-submenu-toggle="hover">
                <a href="{{ route('scholarship.index') }}" class="m-menu__link m-menu__toggle">
                    <i class="m-menu__link-icon flaticon-list-1"></i>
                    <span class="m-menu__link-text">
                        Scholarship
                    </span>
                </a>
            </li>
            <li class="m-menu__item" aria-haspopup="true" data-menu-submenu-toggle="hover">
                <a href="{{ route('forum.index') }}" class="m-menu__link m-menu__toggle">
                    <i class="m-menu__link-icon flaticon-list-1"></i>
                    <span class="m-menu__link-text">
                        Forum
                    </span>
                </a>
            </li>
            <li class="m-menu__item" aria-haspopup="true" data-menu-submenu-toggle="hover">
                <a href="{{ route('subscriber.index') }}" class="m-menu__link m-menu__toggle">
                    <i class="m-menu__link-icon flaticon-mail"></i>
                    <span class="m-menu__link-text">
                        Subscriber
                    </span>
                </a>
            </li>
            <li class="m-menu__item" aria-haspopup="true" data-menu-submenu-toggle="hover">
                <a href="{{ route('configuration.index') }}" class="m-menu__link m-menu__toggle">
                    <i class="m-menu__link-icon flaticon-settings-1"></i>
                    <span class="m-menu__link-text">
                        Configuration
                    </span>
                </a>
            </li>
            <li class="m-menu__item" aria-haspopup="true" data-menu-submenu-toggle="hover">
                <a href="{{ route('administrator.index') }}" class="m-menu__link m-menu__toggle">
                    <i class="m-menu__link-icon flaticon-user"></i>
                    <span class="m-menu__link-text">
                        Administator
                    </span>
                </a>
            </li>
        </ul>
    </div>
</div>